version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
 
linters:
  default: standard
  enable:
    - bodyclose
    - dupl
    - errorlint
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - misspell
    - nestif
    - nolintlint
    - prealloc
    - revive
    - thelper
    - unconvert
    - unparam
    - usetesting

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    nestif:
      min-complexity: 5

    gocritic:
      enable-all: true

    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: package-comments
        - name: var-naming
        - name: unexported-return
        - name: errorf
        - name: error-return
        - name: error-strings
        - name: receiver-naming
        - name: increment-decrement
        - name: error-naming

formatters:
  enable:
    - gofmt
    - goimports
