// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicCitationsConfig } from "./AnthropicCitationsConfig";
import type { CacheControlEphemeral } from "./CacheControlEphemeral";

export type AnthropicFileMessagePartConfig = { cache_control?: CacheControlEphemeral, citations?: AnthropicCitationsConfig, context?: string, title?: string, extra?: Record<string, unknown>, };
