// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CacheControlEphemeral } from "./CacheControlEphemeral";

export type AnthropicMessagePartConfig = { cache_control?: CacheControlEphemeral, extra?: any, };
