// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";
import type { SourceType } from "./SourceType";

export type AssistantContentPart = { "type": "text", text: string, } | { "type": "file", data: string, mimeType: string, provider_options?: ProviderOptions, } | { "type": "source", sourceType: SourceType, id: string, url?: string, title?: string, filename?: string, provider_options?: ProviderOptions, } | { "type": "tool-call", id: string, name: string, args: any, };
