// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";
import type { TextContentPart } from "./TextContentPart";

/**
 * Assistant content parts - text, file, reasoning, tool calls, and tool results allowed
 */
export type AssistantContentPart = { "type": "text" } & TextContentPart | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, filename?: string, media_type: string, provider_options?: ProviderOptions, } | { "type": "reasoning", text: string, 
/**
 * Providers will occasionally return encrypted content for reasoning parts which can
 * be useful when you send a follow up message.
 */
encrypted_content?: string, } | { "type": "toolCall", tool_call_id: string, tool_name: string, input: any, provider_options?: ProviderOptions, provider_executed?: boolean, } | { "type": "toolResult", tool_call_id: string, tool_name: string, output: any, provider_options?: ProviderOptions, };
