// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";
import type { TextContentPart } from "./TextContentPart";

/**
 * Assistant content parts - text, file, reasoning, tool calls, and tool results allowed
 */
export type AssistantContentPart = { "type": "text" } & TextContentPart | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, filename?: string, mediaType: string, providerOptions?: ProviderOptions, } | { "type": "reasoning", text: string, providerOptions?: ProviderOptions, } | { "type": "tool-call", toolCallId: string, toolName: string, input: any, providerOptions?: ProviderOptions, providerExecuted?: boolean, } | { "type": "tool-result", toolCallId: string, toolName: string, output: any, providerOptions?: ProviderOptions, };
