// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelV2AssistantContent } from "./LanguageModelV2AssistantContent";

/**
 * Assistant content that can be either string or array (matching AI SDK beta)
 */
export type AssistantContentValue = string | Array<LanguageModelV2AssistantContent>;
