// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockGuardrailAssessment } from "./BedrockGuardrailAssessment";

export interface BedrockGuardrailTrace { action?: string, input_assessments?: Array<BedrockGuardrailAssessment>, output_assessments?: Array<BedrockGuardrailAssessment>, }