// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockToolResultContent } from "./BedrockToolResultContent";
import type { BedrockToolResultStatus } from "./BedrockToolResultStatus";

export interface BedrockToolResultBlock { tool_use_id: string, content: Array<BedrockToolResultContent>, status?: BedrockToolResultStatus, }