// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockContentBlock } from "./BedrockContentBlock";
import type { BedrockConversationRole } from "./BedrockConversationRole";

export interface BedrockMessage { role: BedrockConversationRole, content: Array<BedrockContentBlock>, }