// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockToolChoice = { "type": "auto" } | { "type": "any" } | { "type": "tool", name: string, };