// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockImageBlock } from "./BedrockImageBlock";
import type { BedrockToolResultBlock } from "./BedrockToolResultBlock";
import type { BedrockToolUseBlock } from "./BedrockToolUseBlock";

export type BedrockContentBlock = { "type": "text", text: string, } | { "type": "image", image: BedrockImageBlock, } | { "type": "toolUse", tool_use: BedrockToolUseBlock, } | { "type": "toolResult", tool_result: BedrockToolResultBlock, };