// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockOutputToolUse } from "./BedrockOutputToolUse";

export type BedrockOutputContentBlock = { "type": "text", text: string, } | { "type": "toolUse", tool_use: BedrockOutputToolUse, };