// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface BedrockInferenceConfiguration { max_tokens?: number, temperature?: number, top_p?: number, stop_sequences?: Array<string>, }