// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockContentPolicyAssessment } from "./BedrockContentPolicyAssessment";
import type { BedrockSensitiveInformationPolicyAssessment } from "./BedrockSensitiveInformationPolicyAssessment";
import type { BedrockTopicPolicyAssessment } from "./BedrockTopicPolicyAssessment";
import type { BedrockWordPolicyAssessment } from "./BedrockWordPolicyAssessment";

export interface BedrockGuardrailAssessment { content_policy?: BedrockContentPolicyAssessment, sensitive_information_policy?: BedrockSensitiveInformationPolicyAssessment, topic_policy?: BedrockTopicPolicyAssessment, word_policy?: BedrockWordPolicyAssessment, }