// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockToolInputSchema } from "./BedrockToolInputSchema";

export interface BedrockToolSpec { name: string, description?: string, input_schema: BedrockToolInputSchema, }