// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockContentBlockStart = { "type": "toolUse", tool_use_id: string, name: string, };