// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockTopic } from "./BedrockTopic";

export interface BedrockTopicPolicyAssessment { topics?: Array<BedrockTopic>, }