// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockTool } from "./BedrockTool";
import type { BedrockToolChoice } from "./BedrockToolChoice";

export interface BedrockToolConfiguration { tools: Array<BedrockTool>, tool_choice?: BedrockToolChoice, }