// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockStopReason = "end_turn" | "max_tokens" | "stop_sequence" | "tool_use" | "content_filtered";