// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockPIIEntity } from "./BedrockPIIEntity";
import type { BedrockRegexMatch } from "./BedrockRegexMatch";

export interface BedrockSensitiveInformationPolicyAssessment { pii_entities?: Array<BedrockPIIEntity>, regexes?: Array<BedrockRegexMatch>, }