// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockCustomWord } from "./BedrockCustomWord";
import type { BedrockManagedWordList } from "./BedrockManagedWordList";

export interface BedrockWordPolicyAssessment { custom_words?: Array<BedrockCustomWord>, managed_word_lists?: Array<BedrockManagedWordList>, }