// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockToolSpec } from "./BedrockToolSpec";

export interface BedrockTool { tool_spec: BedrockToolSpec, }