// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockImageBlock } from "./BedrockImageBlock";

export type BedrockToolResultContent = { "type": "text", text: string, } | { "type": "json", json: any, } | { "type": "image", image: BedrockImageBlock, };