// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockGuardrailTrace } from "./BedrockGuardrailTrace";

export interface BedrockGuardrailConfiguration { guardrail_identifier: string, guardrail_version: string, trace?: BedrockGuardrailTrace, }