// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BedrockContentBlockDelta = { "type": "text", text: string, } | { "type": "toolUse", input: string, };