// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationPosition } from "./CitationPosition";
import type { CitationSource } from "./CitationSource";

export type Citation = { cited_text?: string, position: CitationPosition, source: CitationSource, };
