// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceType } from "./SourceType";

export type CitationSource = { url?: string, title?: string, document_title?: string, document_index?: bigint, license?: string, source_type: SourceType, };
