// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceType } from "./SourceType";

export interface CitationSource { url: string | null, title: string | null, document_title: string | null, document_index: bigint | null, license: string | null, source_type: SourceType, }