// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockGuardrailConfiguration } from "./BedrockGuardrailConfiguration";
import type { BedrockInferenceConfiguration } from "./BedrockInferenceConfiguration";
import type { BedrockMessage } from "./BedrockMessage";
import type { BedrockSystemContentBlock } from "./BedrockSystemContentBlock";
import type { BedrockToolConfiguration } from "./BedrockToolConfiguration";
import type { PromptVariableValues } from "./PromptVariableValues";

export interface ConverseStreamRequest { model_id: string, messages: Array<BedrockMessage>, system?: Array<BedrockSystemContentBlock>, inference_config?: BedrockInferenceConfiguration, tool_config?: BedrockToolConfiguration, guardrail_config?: BedrockGuardrailConfiguration, additional_model_response_field_paths?: Array<string>, prompt_variables?: Record<string, PromptVariableValues>, }