// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockContentBlockDelta } from "./BedrockContentBlockDelta";
import type { BedrockContentBlockStart } from "./BedrockContentBlockStart";
import type { BedrockConverseMetrics } from "./BedrockConverseMetrics";
import type { BedrockStopReason } from "./BedrockStopReason";
import type { BedrockTokenUsage } from "./BedrockTokenUsage";

export type ConverseStreamResponse = { "type": "messageStart", role: string, } | { "type": "contentBlockStart", content_block_index: number, start: BedrockContentBlockStart, } | { "type": "contentBlockDelta", content_block_index: number, delta: BedrockContentBlockDelta, } | { "type": "contentBlockStop", content_block_index: number, } | { "type": "messageStop", stop_reason: BedrockStopReason, } | { "type": "metadata", usage: BedrockTokenUsage, metrics: BedrockConverseMetrics, };