// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BedrockConverseMetrics } from "./BedrockConverseMetrics";
import type { BedrockConverseOutput } from "./BedrockConverseOutput";
import type { BedrockConverseTrace } from "./BedrockConverseTrace";
import type { BedrockStopReason } from "./BedrockStopReason";
import type { BedrockTokenUsage } from "./BedrockTokenUsage";

export interface ConverseResponse { output: BedrockConverseOutput, stop_reason: BedrockStopReason, usage: BedrockTokenUsage, metrics: BedrockConverseMetrics, trace?: BedrockConverseTrace, }