// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CostInfo { total_cost: number, input_cost: number, output_cost: number, cache_cost?: number, reasoning_cost?: number, currency: string, }