// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64Data } from "./Base64Data";

export type FileData = { "type": "url" } & string | { "type": "base_64" } & Base64Data | { "type": "file_id" } & string;