// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * File content part of a message
 */
export type FilePart = { type: 'file', data: string | Uint8Array | ArrayBuffer | Buffer | URL, filename?: string, mediaType: string, providerOptions?: ProviderOptions, };
