// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Generated file content part - matching AI SDK GeneratedFile
 */
export type GeneratedFileContentPart = { file: string | Uint8Array | ArrayBuffer | Buffer | URL, providerMetadata?: ProviderMetadata, };
