// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GoogleConfig { cached_content?: string, safety_settings?: any, extra?: any, }