// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * Image content part of a message
 */
export type ImagePart = { type: 'image', image: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType?: string, providerOptions?: ProviderOptions, };
