// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedV2ProviderMetadata } from "./SharedV2ProviderMetadata";

/**
 * Assistant content - text, file, reasoning, tool calls, and tool results allowed
 */
export type LanguageModelV2AssistantContent = { "type": "text", text: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "reasoning", text: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, filename?: string, mediaType: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "tool-call", toolCallId: string, toolName: string, input: any, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "tool-result", toolCallId: string, toolName: string, output: any, isError?: boolean, providerMetadata?: SharedV2ProviderMetadata, };
