// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelV2Content } from "./LanguageModelV2Content";
import type { SharedV2ProviderOptions } from "./SharedV2ProviderOptions";

/**
 * Exact port of LanguageModelV2Message from Vercel AI SDK
 */
export type LanguageModelV2Message = { "role": "system", content: string, providerOptions?: SharedV2ProviderOptions, } | { "role": "user", content: Array<LanguageModelV2Content>, providerOptions?: SharedV2ProviderOptions, } | { "role": "assistant", content: Array<LanguageModelV2Content>, providerOptions?: SharedV2ProviderOptions, } | { "role": "tool", content: Array<LanguageModelV2Content>, providerOptions?: SharedV2ProviderOptions, };
