// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantContentValue } from "./AssistantContentValue";
import type { LanguageModelV2ToolContent } from "./LanguageModelV2ToolContent";
import type { SharedV2ProviderOptions } from "./SharedV2ProviderOptions";
import type { UserContentValue } from "./UserContentValue";

/**
 * Exact port of LanguageModelV2Message from Vercel AI SDK
 */
export type LanguageModelV2Message = { "role": "system", content: string, providerOptions?: SharedV2ProviderOptions, } | { "role": "user", content: UserContentValue, providerOptions?: SharedV2ProviderOptions, } | { "role": "assistant", content: AssistantContentValue, providerOptions?: SharedV2ProviderOptions, } | { "role": "tool", content: Array<LanguageModelV2ToolContent>, providerOptions?: SharedV2ProviderOptions, };
