// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";
import type { SourceType } from "./SourceType";

/**
 * Legacy content union type - deprecated
 */
export type LanguageModelV2Content = { "type": "text", text: string, providerMetadata?: ProviderMetadata, } | { "type": "reasoning", text: string, providerMetadata?: ProviderMetadata, } | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType: string, providerMetadata?: ProviderMetadata, } | { "type": "source", sourceType: SourceType, id: string, url?: string, title?: string, filename?: string, mediaType?: string, providerMetadata?: ProviderMetadata, } | { "type": "tool-call", toolCallId: string, toolName: string, input: any, providerMetadata?: ProviderMetadata, } | { "type": "tool-result", toolCallId: string, toolName: string, output: any, isError?: boolean, providerMetadata?: ProviderMetadata, };
