// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Legacy tool content - deprecated
 */
export type LanguageModelV2ToolContent = { "type": "tool-result", toolCallId: string, toolName: string, output: any, isError?: boolean, providerMetadata?: ProviderMetadata, };
