// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Legacy user content - deprecated
 */
export type LanguageModelV2UserContent = { "type": "text", text: string, providerMetadata?: ProviderMetadata, } | { "type": "image", image: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType?: string, providerMetadata?: ProviderMetadata, } | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType: string, providerMetadata?: ProviderMetadata, };
