// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedV2ProviderMetadata } from "./SharedV2ProviderMetadata";

/**
 * Role-specific content types matching AI SDK exactly
 * User content - only text and file parts allowed
 */
export type LanguageModelV2UserContent = { "type": "text", text: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "image", image: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType?: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, mediaType: string, providerMetadata?: SharedV2ProviderMetadata, };
