// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedV2ProviderMetadata } from "./SharedV2ProviderMetadata";

/**
 * Tool content - only tool results allowed
 */
export type LanguageModelV2ToolContent = { "type": "tool-result", toolCallId: string, toolName: string, output: any, isError?: boolean, providerMetadata?: SharedV2ProviderMetadata, };
