// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelV2SourceType } from "./LanguageModelV2SourceType";
import type { SharedV2ProviderMetadata } from "./SharedV2ProviderMetadata";

/**
 * Exact port of LanguageModelV2Content union type
 */
export type LanguageModelV2Content = { "type": "text", text: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "reasoning", text: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "file", data: string, mimeType: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "source", sourceType: LanguageModelV2SourceType, id: string, url?: string, title?: string, filename?: string, mediaType?: string, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "tool-call", id: string, name: string, args: any, providerMetadata?: SharedV2ProviderMetadata, } | { "type": "tool-result", toolCallId: string, result: any, isError?: boolean, providerMetadata?: SharedV2ProviderMetadata, };
