// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantContentPart } from "./AssistantContentPart";
import type { ProviderOptions } from "./ProviderOptions";
import type { ToolResultPart } from "./ToolResultPart";
import type { UserContentPart } from "./UserContentPart";

export type Message = { "role": "system", content: string, provider_options?: ProviderOptions, } | { "role": "user", content: Array<UserContentPart>, provider_options?: ProviderOptions, } | { "role": "assistant", content: Array<AssistantContentPart>, provider_options?: ProviderOptions, } | { "role": "tool", content: Array<ToolResultPart>, provider_options?: ProviderOptions, };
