// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";
import type { MessageMetadata } from "./MessageMetadata";
import type { MessageRole } from "./MessageRole";

export interface Message { role: MessageRole, content: Array<ContentBlock>, metadata?: MessageMetadata, }