// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantContentPart } from "./AssistantContentPart";
import type { ProviderMessagePartConfig } from "./ProviderMessagePartConfig";
import type { ToolContentPart } from "./ToolContentPart";
import type { UserContentPart } from "./UserContentPart";

export type Message = { "role": "system", content: string, provider_config?: ProviderMessagePartConfig, } | { "role": "user", content: Array<UserContentPart>, provider_config?: ProviderMessagePartConfig, } | { "role": "assistant", content: Array<AssistantContentPart>, provider_config?: ProviderMessagePartConfig, } | { "role": "tool", content: Array<ToolContentPart>, provider_config?: ProviderMessagePartConfig, };
