// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostInfo } from "./CostInfo";
import type { TokenUsage } from "./TokenUsage";

export interface MessageMetadata { id?: string, timestamp?: bigint, usage?: TokenUsage, cost?: CostInfo, provider_state?: Record<string, any>, reasoning_context?: string, cache_key?: string, }