// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantContent } from "./AssistantContent";
import type { ToolContentPart } from "./ToolContentPart";
import type { UserContent } from "./UserContent";

/**
 * Universal ModelMessage from AI SDK - user-facing format
 */
export type ModelMessage = { "role": "system", content: string, } | { "role": "user", content: UserContent, } | { "role": "assistant", content: AssistantContent, } | { "role": "tool", content: Array<ToolContentPart>, };
