// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantContent } from "./AssistantContent";
import type { ProviderOptions } from "./ProviderOptions";
import type { ToolResultPart } from "./ToolResultPart";
import type { UserContent } from "./UserContent";

/**
 * Universal ModelMessage from AI SDK - user-facing format
 */
export type ModelMessage = { "role": "system", content: string, providerOptions?: ProviderOptions, } | { "role": "user", content: UserContent, providerOptions?: ProviderOptions, } | { "role": "assistant", content: AssistantContent, providerOptions?: ProviderOptions, } | { "role": "tool", content: Array<ToolResultPart>, providerOptions?: ProviderOptions, };
