// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpenAIImageDetail } from "./OpenAIImageDetail";

export type OpenAIFileMessagePartConfig = { filename?: string, detail?: OpenAIImageDetail, extra?: Record<string, unknown>, };
