// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicMessagePartConfig } from "./AnthropicMessagePartConfig";
import type { ExtraMessagePartConfig } from "./ExtraMessagePartConfig";

export interface ProviderMessagePartConfig { anthropic?: AnthropicMessagePartConfig, openai?: ExtraMessagePartConfig, google?: ExtraMessagePartConfig, bedrock?: ExtraMessagePartConfig, other?: Record<string, any>, }