// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicProviderOptions } from "./AnthropicProviderOptions";
import type { GenericProviderOptions } from "./GenericProviderOptions";

export type ProviderOptions = { anthropic?: AnthropicProviderOptions, openai?: GenericProviderOptions, google?: GenericProviderOptions, bedrock?: GenericProviderOptions, other?: Record<string, Record<string, unknown>>, };
