// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicFileMessagePartConfig } from "./AnthropicFileMessagePartConfig";
import type { ExtraMessagePartConfig } from "./ExtraMessagePartConfig";
import type { OpenAIFileMessagePartConfig } from "./OpenAIFileMessagePartConfig";

export type ProviderFileMessagePartConfig = { anthropic?: AnthropicFileMessagePartConfig, openai?: OpenAIFileMessagePartConfig, google?: ExtraMessagePartConfig, bedrock?: ExtraMessagePartConfig, other?: Record<string, Record<string, unknown>>, };
