// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provider options - matching AI SDK ModelMessage format
 */
export type ProviderOptions = Record<string, any>;
