// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnthropicConfig } from "./AnthropicConfig";
import type { BedrockConfig } from "./BedrockConfig";
import type { GoogleConfig } from "./GoogleConfig";
import type { OpenAIConfig } from "./OpenAIConfig";

export interface ProviderMessagePartConfig { anthropic?: AnthropicConfig, openai?: OpenAIConfig, google?: GoogleConfig, bedrock?: BedrockConfig, other?: Record<string, any>, }