// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * Reasoning content part of a message
 */
export type ReasoningPart = { type: 'reasoning', text: string, providerOptions?: ProviderOptions, };
