// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";
import type { ResponseContentPart } from "./ResponseContentPart";

/**
 * Response message - the output equivalent of ModelMessage with rich metadata
 * This includes all the sources, reasoning, etc. that get stripped when converting to ModelMessage
 */
export type ResponseMessage = { role: string, content: Array<ResponseContentPart>, providerOptions?: ProviderOptions, };
