// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";
import type { SourceType } from "./SourceType";

/**
 * Content part for response messages - matches AI SDK's ContentPart exactly
 * This is the output equivalent of ModelMessage content parts
 */
export type ResponseContentPart = { "type": "text", text: string, providerMetadata?: ProviderMetadata, } | { "type": "reasoning", text: string, providerMetadata?: ProviderMetadata, } | { "type": "source", sourceType: SourceType, id: string, url?: string, title?: string, mediaType?: string, filename?: string, providerMetadata?: ProviderMetadata, } | { "type": "file", file: any, providerMetadata?: ProviderMetadata, } | { "type": "tool-call", toolCallId: string, toolName: string, input: any, providerExecuted?: boolean, providerMetadata?: ProviderMetadata, } | { "type": "tool-result", toolCallId: string, toolName: string, output: any, providerMetadata?: ProviderMetadata, } | { "type": "tool-error", toolCallId: string, toolName: string, error: string, providerMetadata?: ProviderMetadata, };
