// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";

export interface SearchResultItem { title: string | null, url: string | null, content: string | null, snippet: string | null, citations?: Array<Citation>, }