// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared provider options - exact port from AI SDK
 */
export type SharedV2ProviderOptions = Record<string, any>;
