// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Source content part - matching AI SDK Source type
 */
export type SourceContentPart = { "sourceType": "url", id: string, url: string, title?: string, providerMetadata?: ProviderMetadata, } | { "sourceType": "document", id: string, mediaType: string, title: string, filename?: string, providerMetadata?: ProviderMetadata, };
