// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source type enum - matches AI SDK Source sourceType
 */
export type SourceType = "url" | "document";
