// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * Text content part of a message
 */
export type TextPart = { type: 'text', text: string, providerOptions?: ProviderOptions, };
