// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tool = "WebSearch" | "CodeExecution" | "FileProcessing" | "ImageGeneration" | "AudioProcessing" | { "ProviderSpecific": string };