// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMessagePartConfig } from "./ProviderMessagePartConfig";
import type { ToolResultContent } from "./ToolResultContent";

export type ToolContentPart = { "type": "tool_result", tool_use_id: string, content?: Array<ToolResultContent>, is_error?: boolean, provider_config?: ProviderMessagePartConfig, };
