// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Tool error content part for response messages
 */
export type ToolErrorContentPart = { toolCallId: string, toolName: string, error: string, providerMetadata?: ProviderMetadata, };
