// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultContent } from "./ToolResultContent";

export type ToolResultPart = { "type": "tool-result", toolCallId: string, result: ToolResultContent, isError?: boolean, };
