// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * Tool result content part of a message
 */
export type ToolResultPart = { type: 'tool-result', toolCallId: string, toolName: string, output: any, providerOptions?: ProviderOptions, };
