// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExecutionType } from "./ToolExecutionType";

export interface ToolDefinition { name: string, description: string, input_schema: Record<string, any>, execution_type: ToolExecutionType, provider_config?: Record<string, any>, }