// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderMetadata } from "./ProviderMetadata";

/**
 * Tool call content part for response messages
 */
export type ToolCallContentPart = { toolCallId: string, toolName: string, input: any, providerExecuted?: boolean, providerMetadata?: ProviderMetadata, };
