// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolExecutionType } from "./ToolExecutionType";

export interface ToolCall { id: string, tool_name: string, arguments: Record<string, any>, execution_type: ToolExecutionType, }