// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tool } from "./Tool";

export interface ToolConfig { tool: Tool, config?: Record<string, any>, max_uses?: number, }