// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";

/**
 * Tool call content part of a message
 */
export type ToolCallPart = { type: 'tool-call', toolCallId: string, toolName: string, input: any, providerOptions?: ProviderOptions, providerExecuted?: boolean, };
