// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ToolResult { call_id: string, success: boolean, result: Record<string, any>, error?: string, metadata?: Record<string, any>, }