// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { FileData } from "./FileData";

export type ToolResultContent = { "type": "text", text: string, citations?: Array<Citation>, } | { "type": "image", data: FileData, } | { "type": "json", json: any, };
