// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostInfo } from "./CostInfo";
import type { TokenUsage } from "./TokenUsage";

export interface Usage { tokens: TokenUsage, cost?: CostInfo, provider: string, model: string, }