// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { FileData } from "./FileData";
import type { ProviderFileMessagePartConfig } from "./ProviderFileMessagePartConfig";
import type { ProviderMessagePartConfig } from "./ProviderMessagePartConfig";

export type UserContentPart = { "type": "text", text: string, citations?: Array<Citation>, provider_config?: ProviderMessagePartConfig, } | { "type": "file", data: FileData, mime_type: string, provider_config?: ProviderFileMessagePartConfig, };
