// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LanguageModelV2UserContent } from "./LanguageModelV2UserContent";

/**
 * User content that can be either string or array (matching AI SDK beta)
 */
export type UserContentValue = string | Array<LanguageModelV2UserContent>;
