// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderOptions } from "./ProviderOptions";
import type { TextContentPart } from "./TextContentPart";

/**
 * User content parts - text, image, and file parts allowed
 */
export type UserContentPart = { "type": "text" } & TextContentPart | { "type": "image", image: string | Uint8Array | ArrayBuffer | Buffer | URL, media_type?: string, provider_options?: ProviderOptions, } | { "type": "file", data: string | Uint8Array | ArrayBuffer | Buffer | URL, filename?: string, media_type: string, provider_options?: ProviderOptions, };
