// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserContentPart } from "./UserContentPart";

/**
 * User content that can be either string or array (matching AI SDK ModelMessage)
 */
export type UserContent = string | Array<UserContentPart>;
