// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";

export interface WebSearchResultItem { title: string | null, url: string, snippet: string | null, display_url: string | null, publish_date: string | null, citations?: Array<Citation>, }