// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";

export type WebSearchResultItem = { title?: string, url: string, snippet?: string, display_url?: string, publish_date?: string, citations?: Array<Citation>, };
