// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Capabilities { web_search: boolean, code_execution: boolean, file_processing: boolean, image_generation: boolean, reasoning: boolean, context_caching: boolean, streaming: boolean, tool_calling: boolean, }