// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CitationPosition = { "type": "char_range", start: bigint, end: bigint, } | { "type": "page_range", start_page: bigint, end_page: bigint, } | { "type": "block_range", start_block: bigint, end_block: bigint, } | { "type": "search_index", index: bigint, };