// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentType } from "./ContentType";

export interface ContentBlock { content_type: ContentType, data: string, metadata?: Record<string, any>, }