// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";

export interface ProviderCapabilities { provider: string, capabilities: Capabilities, models: Array<string>, }