// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TokenUsage { input_tokens: bigint, output_tokens: bigint, total_tokens: bigint, reasoning_tokens?: bigint, cached_tokens?: bigint, provider_breakdown?: Record<string, any>, }